### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by KathiSchleidt** [INSIDE-information-systems/WFS3#12]
Started with the question if Feature IDs be strings or must be numeric - GeoServer is treating them as strings.
However, this would require some additional constraints (no / in the string ID) to assure clean URI paths (otherwise IDs such as "abc/xyz" will cause issues), example from Hylke:
`wfs3/collections/http://hylke.org/ns/items/items/http://hylke.org/ns/items/item66`

**Comment by sgrellet** [comment]
Two things from ou point of view
* with Feature IDs, do you refer to "id" or "identifier" ? using HTTP URIs, one should not use '/' other than to fragment the URI.
With this in mind we go for 
	 - "identifier": https://data.geoscience.fr/id/well/BSS000AAAA
	- "id" (just the trailing part)-> "id": "BSS000AAAA",
* which FeatureCollection should have a URI ?
	- those allowing to explore the content of the API -> basically based on the API URI (https://data.geoscience.fr/api/well): we would say yes 
	- those dynamically generated as a response to a WFS 3 query : we need to evaluate whether they should be 'persistent'

**Comment by KathiSchleidt** [comment]
Some questions on how to adjust the mapping to get the correct ID behaviour.
I'm happy with Sylvains approach of:

-     "identifier": https://data.geoscience.fr/id/well/BSS000AAAA
-     "id" (just the trailing part)-> "id": "BSS000AAAA",

Just not quite clear what should really be provided under identifier, always adding "https://data.geoscience.fr/id/well/" as prefix to the bss_id doesn't work as we have identifiers on sub-features:

```
"identifier": {
	"value": "https://data.geoscience.fr/id/well/BSS000AAAA",
	"@codeSpace": "http://www.ietf.org/rfc/rfc2616"
},
```
And - at present, id is still being filled with indice (this was a practical hack to see if data was coming through correctly, as the bss_id is harder to join into the DB views), reason we have "id": "0001000001"
I'll fix this when I add the URL Prefix to identifiers.

But - first we must decide on the prefix URL, we have the following identifiers
- eposb:Alias
- eposb:Borehole

And - to my view, gwml-wellconstruction:BoreCollar should actually also have an identifier (currently missing in the mapping, but as this is a feature...)

**Comment by sgrellet** [comment]
Regarding **'bss_id**', it will work to feed the "https://data.geoscience.fr/id/well/BSS000AAAA" pattern for the gml:identifier of the feature Borehole

**eposb:Alias** is the identifier in other systems.
Most of them are not in a URI approach, so just the identifier that is in the DB (with no prefix will suffice).

**gwml-wellconstruction:BoreCollar** : you're right but we'll add it at a later stage. so far we 'just' need it to have the collarLocation

**Comment by KathiSchleidt** [comment]
I've changed the base id back to bss_id (I'd had indice there as it was easier to debug, quick access to DB record). I'll reload the config after I've done a few more small fixes
