### ISSUE TITLE
Adding data type information into the GeoJSON output, some comments

### ISSUE THREAD

**Issue by aaime** [INSIDE-information-systems/WFS3#14]
I would like to double check with you the current progress of the GeoServer GeoJSON output.
The current output I have (in my developer version, on my machine, not they committed) looks as follows:
https://gist.githubusercontent.com/aaime/13b76b8c5c012fd6916d6271889a7e4e/raw/dccebc2f942f80da7e27cf5975a72de6de19d10a/borehole.json

The reference you gave us looks like this instead:
https://raw.githubusercontent.com/INSIDE-information-systems/WFS3/master/GML_GeoJSON_JSONLD/target_borehole_wfs3_output.json

There are a few differences that I want to discuss:

- The "featureType" attribute is currently placed at the top level of a feature, alongside id, type and geometry, which eliminates chance of conflicts with valid property names, which could have occurred following the suggested output
- The "dataType" attribute is placed inside the objects, but named "@dataType" to reduce the chance of conflicts (it would conflict only with a same named XML attributes, thankfully attributes are not used all that much outside of specific cases, e.g., codelists, linking)
- The objects of type "ReferenceType" have a ``"@datatype" : "Reference"`` to avoid piling up exceptions in the code, which would just make it brittle (someone else could find exceptions later down the road).. I would like to keep it like that if at all possible, does not seem like the extra data type adds much noise and allows the JSON client to understand it's working against a link right away.

Do you have strong objections to any of the above?

**Comment by KathiSchleidt** [comment]
Hi Andrea, perfect timing as I've been trying to formalize the transformation from GML321 to GeoJSON rules. Some thoughts from my side:
* Always having featureType at the base level of the object is far cleaner to my view, reason we pushed it down to the properties was fear of upsetting GeoJSON (can one add additional attributes other than in the properties object?)
* I understand adding the @ to @datatype, but could we then also add it to @featuretype for consistency?
* Defining the fine line as to which types are provided, which left out for brevity has been my main conundrum. I'm very happy to drop simple types such as gco:CharacterString, but the reference types are for me already a fine line. I think I'd be happiest with everything that is an object with more than one attribute being typed, but I remember being overruled at the meeting in Orleans (forgetten why though :( @sgrellet can you remember?). Especially if we add Reference as a datatype, it doesn't make sense not to do the same for types such as Measure

**Comment by aaime** [comment]
Answering point by point:

- FeatureType: the GeoJSON specification does not say anything about adding extra attributes, the WFS3 spec actually used that quite liberally to add links and other things into the WFS3 GeoJSON output flavor
- @featureType: sure I can go for that, my initial reasoning is that ``@`` was sort of a protection against conflict and an indicator that something is an XML attribute, so it was really needed in a non controlled enviroment (the GeoJSON encoder is really blind, does not know about schemas at all)
- Deciding what to include: the encoder is not there specifically to serve translation from GML features, it will encode any complex feature setup (app-schema being one example, but there are others, like for example the complex features generated by the OpenSearch plugin, which are not originating from a GML schema, but hand coded instead). Let's also consider this encoder is in core, it's not a specific module. So I'd try to keep GML knowledge to a minimum, the code to recognize the property/element "polka steps" is already an example of ugly GML specific guesswork in there (and has no firm reference, GML gives none, properties do not extend a common base, it's just based on a property naming heuristics).

**Comment by sgrellet** [comment]
We have compared the two files with @afeliachi.
Below are answers to the points raised in this issue. For the other we created issue #15  (and also contributed to #12)

* @featureType outside properties
We initially decided to have them in properties so that the information is not ignored by GeoJSON parsers (test done using http://geojson.io/).
We consider that knowing that this is a 'Borehole' featureType is a valuable piece of information

* dataType: 
We put @ in the first place to identify xml attributes (ex : @srsName, @codeList, ...)
+1 for @dataType and @featuretype

* "@dataType": "Reference" for every gml:ReferenceType
+1. 

* "@dataType": "Reference", "@dataType": "Measure" name
	* regarding Kathi's comment on Measure: it's in Andrea's sample file.
	* we are fine with the consistent pattern, just wondering why not reusing something closer to the exact name in GML ? For example (just replacing the ':' with '_'): "@dataType": "gml_ReferenceType", "@dataType": "gml_MeasureType", might help maintain 'semantic consistency no ? however, looking at ISO 19103 the class is called "Measure" and same goes for the 'Reference' -> @aaime : is that the reason ?
	* other question (sorry) : we define here a had'oc naming convention that we try to keep as generic as possible (+ the fact that this encoder is in core). However, is there another writing convention we should consider (ex : in SensorThingsAPI building on @odata.navigationLink Oasis specs we have @iot.navigationLink) ? Maybe we are trying to mix toooo many things :)

**Comment by aaime** [comment]
Ok with putting featureType among properties, more chance of conflicts but it's not good if existing parsers would ignore it.

About the type naming I simply followed [your target example](https://raw.githubusercontent.com/INSIDE-information-systems/WFS3/master/GML_GeoJSON_JSONLD/target_borehole_wfs3_output.json), take the GML name, ignore the namespace, remove the "Type" suffix. For example, in GML there is no "Borehole", there is only "BoreholeType", there is no "Custodian" but "CustodianType", and so on. (to be more specific, it's what I have in the in memory object representation of the GML, there is no actual GML nor schemas where the GeoJSON encoder works).

**Comment by sgrellet** [comment]
> About the type naming I simply followed your target example, take the GML name, ignore the namespace, remove the "Type" suffix"

Ok and, the "Type" suffix being added by the GML polka steps then we go back on the class name in the ISO model :) seems we are fine then

And, back to Kathi's last question on the 
> fine line as to which types are provided, which left out for brevity has been my main conundrum.

In Orléans we said we won't provide type for simple Types (see https://github.com/INSIDE-information-systems/WFS3/issues/6#issuecomment-475399225). In that issue, we just added Measure and Reference (that were under question).

**Comment by aaime** [comment]
The code as written recognizes simple types and does not add the @dataType in them, but ReferenceType is not a simple one, from GML 3.2:

```
<complexType name="ReferenceType">
<annotation>
<documentation>
gml:ReferenceType is intended to be used in application schemas directly, if a property element shall use a "by-reference only" encoding.
</documentation>
</annotation>
<sequence/>
<attributeGroup ref="gml:OwnershipAttributeGroup"/>
<attributeGroup ref="gml:AssociationAttributeGroup"/>
</complexType>
```

For full XSD check http://schemas.opengis.net/gml/3.2.1/gmlBase.xsd

**Comment by sgrellet** [comment]
yep that's why they were under question :)
Would that be a good summary to say only simpleType don't have the @dataType. 
Thus all that is complexType in gml (gmlbase and others) will have @dataType.
? 
if we all agree, then I'll properly close the issue (not too fast because of shorcuts like right now) and it will serve as material  for #6

**Comment by aaime** [comment]
The only other exception which is not getting a "dataType" are "complex types with simple content", e.g., the gco:CharacterString.

**Comment by sgrellet** [comment]
You mean like this (from http://schemas.opengis.net/iso/19139/20070417/gco/basicTypes.xsd) ?

 ```xml
	<!-- ........................................................................ -->
	<xs:element name="CharacterString" type="xs:string"/>
	<!-- ........................................................................ -->
	<xs:complexType name="CharacterString_PropertyType">
		<xs:sequence minOccurs="0">
			<xs:element ref="gco:CharacterString"/>
		</xs:sequence>
		<xs:attribute ref="gco:nilReason"/>
	</xs:complexType>
 ```

**Comment by aaime** [comment]
Ah no, that's a "polka step", is a PropertyType, intermediate property to reach the data. That is a different case, sorry, I picked the wrong example.
This one is hopefully better:

```
<complexType name="CodeType">
<annotation>
<documentation>
gml:CodeType is a generalized type to be used for a term, keyword or name. It adds a XML attribute codeSpace to a term, where the value of the codeSpace attribute (if present) shall indicate a dictionary, thesaurus, classification scheme, authority, or pattern for the term.
</documentation>
</annotation>
<simpleContent>
<extension base="string">
<attribute name="codeSpace" type="anyURI"/>
</extension>
</simpleContent>
</complexType>
```

This one does not get a dataType, even when the codeSpace is present.

**Comment by sgrellet** [comment]
Ok. Understood.
I think we can close this issue now
