### ISSUE TITLE
encodeIfEmpty=false not working

### ISSUE THREAD

**Issue by KathiSchleidt** [INSIDE-information-systems/WFS3#22]
For both eposb:boreCollarPositionalAccuracy and eposb:length, I've added <encodeIfEmpty>false</encodeIfEmpty> to see if this helps (should be the default anyway, reason why wasn't there)
Strange thing is that this also happens in XML

**Comment by aaime** [comment]
Debugged through the code, the encodeIfEmpty seems to be working properly, but it's not meant to defy what the schema demands. And the schema says:

```
	<complexType name="BoreholeType">
		<complexContent>
			<extension base="sams:SF_SpatialSamplingFeatureType">
				<sequence>
...
					<element name="boreCollarPositionalAccuracy" type="gml:MeasureType">
						<annotation>
							<documentation>An estimate of the accuracy of the location of the borehole collar location. Ideally, this would be a quantitative estimate of accuracy (e.g., 20 metres).
Note : this attribute should be carried by BoreCollar. A changeRequest to GWML2 OGC SWG has been generated. This attribute acts as a placeholder in between a new version og GWML2 is available</documentation>
						</annotation>
					</element>
...
```

Notice how the element declaration misses both minOccurs and maxOccurs. But by XML schema spec, if missing they both default to 1:
https://www.w3.org/TR/xmlschema-0/#OccurrenceConstraints

So, the element is in the output because the schema mandates its presence.

**Comment by aaime** [comment]
Ah, for verification I went into the app-schema schema cache and hand modified the schema to report:

```
					<element name="boreCollarPositionalAccuracy" minOccurs="0" type="gml:MeasureType">
						<annotation>
							<documentation>An estimate of the accuracy of the location of the borehole collar location. Ideally, this would be a quantitative estimate of accuracy (e.g., 20 metres).
Note : this attribute should be carried by BoreCollar. A changeRequest to GWML2 OGC SWG has been generated. This attribute acts as a placeholder in between a new version og GWML2 is available</documentation>
						</annotation>
					</element>
```

Restarted GeoServer, did the request again, and the element was gone.

**Comment by nmco** [comment]
Can we close this one @KathiSchleidt ?

**Comment by KathiSchleidt** [comment]
Works,thanks for the clarification!
