### ISSUE TITLE
Produce target JSON-LD

### ISSUE THREAD

**Issue by sgrellet** [INSIDE-information-systems/WFS3#4]

**Comment by afeliachi** [comment]
A first version of [the target JSON-LD](https://github.com/INSIDE-information-systems/WFS3/blob/master/GML_GeoJSON_JSONLD/target_borehole_wfs3_output.jsonld) is comminted.
I have an issue with non uri "xlink:href" ([example](https://github.com/INSIDE-information-systems/WFS3/blob/6cd0759b63c5d759871349605525af0c2adda5d1/GML_GeoJSON_JSONLD/borehole_wfs3_gml32.xml#L82)). Not sure how to handle it.

Thoughts ?

**Comment by sgrellet** [comment]
Only remains @afeliachi adjusting the geometry in target_borehole_wfs3_output.jsonld to use wktLiteral and declare SRS

**Comment by afeliachi** [comment]
done. Actually it's not EWKT as we know it in gis DB but the right way to wright a gsp:wkt literal
