### ISSUE TITLE
Should a GetFeature by identifier query return a Featurecollection ?

### ISSUE THREAD

**Issue by sgrellet** [INSIDE-information-systems/WFS3#5]
I know that our example GML file is based on the output of a standard GetFeature query. That's why we have a FeatureCollection to deal with (and find it back in the target GeoJSON output). But in a 'GetFeature by identifier' type of query, given that the feature is unique, can we consider it should not part of a FeatureCollection ? Thus leave this alone in the GeoJSON output ?

**Comment by sgrellet** [comment]
Feature collection is an unnecessary part to parse no matter the serialization

**Comment by aaime** [comment]
The WFS3 specification mandates that when requesting a single feature by id, e.g. "https://server/wfs3/collections/collectionId/items/featureId" then the FeatureCollection elements should be skipped and only the feature returned. I don't think it's working for complex features, but here is an example for simple ones:
https://maps.geo-solutions.it/geoserver/wfs3/collections/syria_vtp__building_s/items/building_s.1?f=application%2Fgeo%2Bjson&limit=50

**Comment by sgrellet** [comment]
great thanks
