### ISSUE TITLE
Serialization of non-URI "xlink:href" values

### ISSUE THREAD

**Issue by afeliachi** [INSIDE-information-systems/WFS3#9]
related to #4

**Comment by sgrellet** [comment]
For eposb:legalAccessLevel "@id": "openaccess", OpenAIRE Guidelines provide help (https://media.readthedocs.org/pdf/guidelines/latest/guidelines.pdf) -> http://purl.org/eprint/accessRights/

For eposb:locatedOnAdminUnit we'll point to the insee rdf URI (like http://id.insee.fr/geo/commune/62774

I'll update the JSON-LD accordingly
